export const ACTION_TYPES = [
  'CREATE_BACKUP',
  'CREATE_WORKSPACE',
  'GENERATE_RUNTIME',
  'GENERATE_FUNCTION',
  'GENERATE_SDK',
  'REWRITE_CODE',
  'UPDATE_IMPORTS',
  'REMOVE_UNUSED_IMPORTS',
  'FORMAT_FILE',
  'VALIDATE_PROJECT',
  'GENERATE_REPORT',
] as const;

export type ActionType = (typeof ACTION_TYPES)[number];

export const ACTION_TYPE_ORDER: Record<ActionType, number> = {
  CREATE_BACKUP: 0,
  CREATE_WORKSPACE: 1,
  GENERATE_RUNTIME: 2,
  GENERATE_SDK: 3,
  GENERATE_FUNCTION: 4,
  REWRITE_CODE: 5,
  UPDATE_IMPORTS: 6,
  REMOVE_UNUSED_IMPORTS: 7,
  FORMAT_FILE: 8,
  VALIDATE_PROJECT: 9,
  GENERATE_REPORT: 10,
};
